#!/usr/bin/env python3
"""Build-time header holding the SIMD4 program bank the digit driver launches.

Both dense kernels are packed into one 256-word image and loaded once. ENTRY then
selects which one a launch runs, so the guest never rewrites program memory: an
accepted START clears lane state but leaves both memories alone.

    python3 -m tools.rv32_digit_kernels build/rv32/digit_kernels.h
"""

from programs.simd4.dense4 import LANES, bank, base_cycles, expected_counts

LAYER1_DEPTH = 49          # 196 inputs as four chunks of 49, the largest chunk that fits
LAYER2_DEPTH = 32          # the whole hidden vector in one chunk
SHAPES = {'layer1': LAYER1_DEPTH, 'layer2': LAYER2_DEPTH}


def kernels():
    """The 256-word program image and the entry point of each kernel."""
    return bank(SHAPES)


def header():
    words, entries = kernels()
    lines = ['/* Generated by tools.rv32_digit_kernels; do not edit. */',
             '#ifndef RV32_DIGIT_KERNELS_H', '#define RV32_DIGIT_KERNELS_H', '#include <stdint.h>', '']
    for name, depth in SHAPES.items():
        instructions, transfers = expected_counts(depth)
        lines += [f'#define DIGIT_{name.upper()}_ENTRY {entries[name]}u',
                  f'#define DIGIT_{name.upper()}_DEPTH {depth}u',
                  f'#define DIGIT_{name.upper()}_INSTRUCTIONS {instructions}u',
                  f'#define DIGIT_{name.upper()}_TRANSFERS {transfers}u',
                  f'/* {base_cycles(depth)} engine cycles with no memory waits. */']
    lines += [f'#define DIGIT_LANES {LANES}u', '',
              'static const uint32_t digit_kernel_bank[256] = {']
    lines += ['    ' + ', '.join(f'0x{w:08x}u' for w in words[i:i + 8]) + ',' for i in range(0, 256, 8)]
    lines += ['};', '', '#endif']
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    import argparse
    from pathlib import Path
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('output', type=Path)
    arguments = parser.parse_args()
    arguments.output.write_text(header())
