#!/usr/bin/env python3
"""Build-time headers holding the integer weights and the diagnostic's expected results.

The weights are emitted once, in *launch order*, so that both guest paths walk the
same table with a moving pointer and neither needs an index multiply:

    layer 1   launch l = chunk * 8 + group        (4 input chunks x 8 output groups)
              slot lane * 49 + j  holds  W1[group * 4 + lane][chunk * 49 + j]
    layer 2   launch l                            (10 classes padded to 12)
              slot lane * 32 + n  holds  W2[l * 4 + lane][n], or 0 for the padding

Writing a launch's weights to the accelerator is then one sequential copy into the
data window, and the CPU reference accumulates in the same order, so the two paths
cannot drift apart through a layout mistake.

    python3 -m tools.rv32_digit_model weights build/rv32/digit_weights.h
    python3 -m tools.rv32_digit_model check   build/rv32/digit_check.h --images 8
"""

import os
from pathlib import Path

from tools import digit_data, digit_ref
from tools.rv32_digit_kernels import LAYER1_DEPTH, LAYER2_DEPTH, header as kernel_header
from programs.simd4.dense4 import LANES

ROOT = Path(__file__).resolve().parents[1]
CHECK_IMAGES = 8


def launch_order_weights(model):
    """Rearrange both weight matrices into the per-launch blocks described above."""
    shape = model['architecture']
    hidden, classes, inputs = shape['hidden'], shape['classes'], shape['inputs']
    chunks, groups = inputs // LAYER1_DEPTH, hidden // LANES
    if chunks * LAYER1_DEPTH != inputs or groups * LANES != hidden:
        raise ValueError('layer 1 does not divide into whole chunks and lane groups')
    first = []
    for chunk in range(chunks):
        for group in range(groups):
            block = []
            for lane in range(LANES):
                row = model['w1'][group * LANES + lane]
                block += row[chunk * LAYER1_DEPTH:(chunk + 1) * LAYER1_DEPTH]
            first.append(block)
    second = []
    for launch in range((classes + LANES - 1) // LANES):
        block = []
        for lane in range(LANES):
            index = launch * LANES + lane
            block += model['w2'][index] if index < classes else [0] * hidden
        second.append(block)
    return first, second


def rows(values, per_line=16):
    return ['    ' + ', '.join(str(v) for v in values[i:i + per_line]) + ','
            for i in range(0, len(values), per_line)]


def shape_header(model=None):
    """Only the dimensions, for the public API headers.

    `digit_model.h` and `digit_ui.h` need the array sizes in their signatures but
    have no business carrying six kilobytes of weights into every translation unit
    that includes the runtime. The weights live in their own header, included by
    the two .c files that actually multiply with them.
    """
    model = model or digit_ref.load_model()
    shape = model['architecture']
    return '\n'.join([
        '/* Generated by tools.rv32_digit_model; do not edit. */',
        '#ifndef RV32_DIGIT_SHAPE_H', '#define RV32_DIGIT_SHAPE_H', '',
        f'#define DIGIT_INPUTS {shape["inputs"]}u',
        f'#define DIGIT_HIDDEN {shape["hidden"]}u',
        f'#define DIGIT_CLASSES {shape["classes"]}u',
        f'#define DIGIT_POOLED {shape["pooled_side"]}u',
        f'#define DIGIT_SIDE {digit_data.SIDE}u',
        f'#define DIGIT_PIXELS {digit_data.PIXELS}u',
        f'#define DIGIT_L1_DEPTH {LAYER1_DEPTH}u',
        f'#define DIGIT_L2_DEPTH {LAYER2_DEPTH}u',
        f'#define DIGIT_LANES {LANES}u',
        '', '#endif']) + '\n'


def _weight_arrays(model):
    """The four array declarations, shared by the header and the definitions file."""
    first, second = launch_order_weights(model)
    return (('int8_t', 'digit_w1[DIGIT_L1_LAUNCHES][DIGIT_L1_BLOCK]', first, 16),
            ('int8_t', 'digit_w2[DIGIT_L2_LAUNCHES][DIGIT_L2_BLOCK]', second, 16),
            ('int32_t', 'digit_b1[DIGIT_HIDDEN]', [model['b1']], 8),
            ('int32_t', 'digit_b2[DIGIT_CLASSES]', [model['b2']], 8))


def weights_source(model=None):
    """The one definition of each weight array.

    These were `static const` in the header, which gave every translation unit that
    included it a private copy: 7,040 bytes of the diagnostic's read-only data and
    6,656 of the capstone image were duplicates. They are defined once here and
    declared `extern` in the header instead.
    """
    model = model or digit_ref.load_model()
    lines = ['/* Generated by tools.rv32_digit_model; do not edit. */',
             '#include "digit_weights.h"', '']
    for kind, declaration, blocks, per_line in _weight_arrays(model):
        lines.append(f'const {kind} {declaration} = {{')
        for block in blocks:
            if len(blocks) > 1:
                lines.append('  {')
            lines += [('  ' if len(blocks) > 1 else '') + row for row in rows(block, per_line)]
            if len(blocks) > 1:
                lines.append('  },')
        lines.append('};')
    return '\n'.join(lines) + '\n'


def weights_header(model=None):
    model = model or digit_ref.load_model()
    shape = model['architecture']
    first, second = launch_order_weights(model)
    shift = model['shift']
    lines = ['/* Generated by tools.rv32_digit_model; do not edit. */',
             '#ifndef RV32_DIGIT_WEIGHTS_H', '#define RV32_DIGIT_WEIGHTS_H', '#include <stdint.h>',
             '#include "digit_shape.h"', '',
             f'#define DIGIT_SHIFT {shift}u',
             f'#define DIGIT_ROUND {(1 << (shift - 1)) if shift else 0}u',
             f'#define DIGIT_HIDDEN_MAX {model["hidden_max"]}u',
             f'#define DIGIT_L1_LAUNCHES {len(first)}u',
             f'#define DIGIT_L2_LAUNCHES {len(second)}u',
             f'#define DIGIT_L1_BLOCK {len(first[0])}u',
             f'#define DIGIT_L2_BLOCK {len(second[0])}u',
             f'#define DIGIT_L1_CHUNKS {shape["inputs"] // LAYER1_DEPTH}u',
             f'#define DIGIT_L1_GROUPS {shape["hidden"] // LANES}u', '']
    lines += ['/* Declared, not defined: the definitions live in digit_weights.c so that',
              '   three translation units do not carry three copies of the tables. */']
    for kind, declaration, _blocks, _per_line in _weight_arrays(model):
        lines.append(f'extern const {kind} {declaration};')
    lines += ['', '#endif']
    return '\n'.join(lines) + '\n'


def check_header(count=CHECK_IMAGES, model=None):
    """Canvases and expected logits for the firmware diagnostic, from the oracle."""
    if count < 1:
        raise ValueError('the diagnostic needs at least one image; zero would report success having checked nothing')
    model = model or digit_ref.load_model()
    images, labels = digit_data.load_test_set()
    lines = ['/* Generated by tools.rv32_digit_model; do not edit. */',
             '#ifndef RV32_DIGIT_CHECK_H', '#define RV32_DIGIT_CHECK_H', '#include <stdint.h>', '',
             f'#define DIGIT_CHECK_IMAGES {count}u', '',
             '/* Raw 28x28 canvases: the guest preprocesses them itself, so its centring',
             '   and pooling are exercised rather than assumed. */',
             f'static const uint8_t digit_check_canvas[DIGIT_CHECK_IMAGES][{digit_data.PIXELS}] = {{']
    for index in range(count):
        lines.append('  {')
        lines += ['  ' + row for row in rows(list(images[index]), 24)]
        lines.append('  },')
    lines += ['};', '',
              'static const int32_t digit_check_logits[DIGIT_CHECK_IMAGES][10] = {']
    computed = [digit_ref.infer(digit_data.prepare(images[index]), model) for index in range(count)]
    for logits in computed:
        lines.append('    {' + ', '.join(str(v) for v in logits) + '},')
    lines += ['};', '', 'static const uint8_t digit_check_expected[DIGIT_CHECK_IMAGES] = {']
    lines.append('    ' + ', '.join(str(digit_ref.argmax(logits)[0]) for logits in computed) + ',')
    lines += ['};', '', '/* The true labels, for reporting only: the diagnostic checks the oracle,',
              '   not the dataset, so a misclassified image is still a passing test. */',
              'static const uint8_t digit_check_label[DIGIT_CHECK_IMAGES] = {']
    lines.append('    ' + ', '.join(str(labels[i]) for i in range(count)) + ',')
    lines += ['};', '', '#endif']
    return '\n'.join(lines) + '\n'


def ensure_headers(directory=None):
    """Regenerate the headers whose content is out of date, and return the directory.

    The make rules are the primary path. This covers the other entry point: a test
    run directly with `python3 -m unittest` has no make step, so on a fresh
    checkout the headers would not exist and on a changed model they would be
    stale. Comparing content rather than timestamps means a run that changes
    nothing rewrites nothing, so this neither churns timestamps nor fights a build
    that is regenerating the same bytes.
    """
    directory = Path(directory or ROOT / 'build/rv32')
    directory.mkdir(parents=True, exist_ok=True)
    for name, produce in (('digit_shape.h', shape_header),
                          ('digit_weights.h', weights_header),
                          ('digit_check.h', check_header),
                          ('digit_kernels.h', kernel_header)):
        target, wanted = directory / name, produce()
        if target.exists() and target.read_text() == wanted:
            continue
        # Write and rename, so an interrupted run cannot leave a half-written header
        # that the next build accepts on its timestamp.
        scratch = target.with_suffix(target.suffix + '.tmp')
        scratch.write_text(wanted)
        os.replace(scratch, target)
    return directory


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('kind', choices=('shape', 'weights', 'weights-source', 'check'))
    parser.add_argument('output', type=Path)
    parser.add_argument('--images', type=int, default=CHECK_IMAGES)
    arguments = parser.parse_args()
    text = {'shape': shape_header, 'weights': weights_header,
            'weights-source': weights_source}.get(arguments.kind)
    text = text() if text else check_header(arguments.images)
    arguments.output.write_text(text)
