"""Reproducible guest kernel header built from the standalone A1 builders."""
from programs.simd4.vector_add import program as vector
from programs.simd4.matrix_mac import program as matrix
from tools.simd4_model import MAC, MACU


def kernels():
    signed = matrix(4, 4, 16)
    unsigned = [(w & 0xffffff) | (MACU << 24) if w >> 24 == MAC else w for w in signed]
    return {'vector': vector(), 'matrix': signed, 'unsigned_matrix': unsigned}


def header():
    lines = ['/* Generated by tools.rv32_simd4_kernels; do not edit. */', '#include <stdint.h>']
    for name, words in kernels().items():
        lines.append(f'static const uint32_t {name}_kernel[256] = {{')
        lines.extend('    ' + ', '.join(f'0x{w:08x}u' for w in words[i:i+8]) + ',' for i in range(0, 256, 8))
        lines.append('};')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    import argparse
    from pathlib import Path
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    args.output.write_text(header())
